from pydantic import BaseModel, Field
from typing import Any, Optional, List

# ==========================================
# 1. Core Document Chunks (Vector Data)
# ==========================================

class DocumentChunkBase(BaseModel):
    document_name: str = Field(..., description="The source file name", example="resume_kyaw_swar_hein.txt")
    language: str = Field(..., description="Language code: 'en' or 'ja'", example="en")
    content: str = Field(..., description="The raw text snippet content")
    extra_metadata: dict[str, Any] = Field(default_factory=dict, description="Arbitrary metadata dict")

class DocumentChunkCreate(DocumentChunkBase):
    pass

class DocumentChunkResponse(DocumentChunkBase):
    id: int

    class Config:
        from_attributes = True

# ==========================================
# 2. Search & Query Request Formats
# ==========================================

class DocumentSearchQuery(BaseModel):
    query: str = Field(..., description="Semantic search natural language text")
    language: Optional[str] = Field(None, description="Filter results strictly to 'en' or 'ja'")
    top_k: int = Field(default=5, ge=1, le=50, description="Number of closest chunks to retrieve")

# ==========================================
# 3. Agent Responses & Source Citations
# ==========================================

class CitationSource(BaseModel):
    id: int = Field(..., description="Database chunk ID")
    document_name: str = Field(..., description="Source document title")
    content: str = Field(..., description="The exact text section matched")

    class Config:
        from_attributes = True

class AgentQueryResponse(BaseModel):
    query: str = Field(..., description="The original screening query sent by the user")
    answer: str = Field(..., description="The synthesized, structured analysis generated by the LLM")
    sources: List[CitationSource] = Field(default_factory=list, description="List of exact context snippets used for grounding")